name: publish

on:
  workflow_dispatch: {}
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install build and test tools
        run: |
          python -m pip install --upgrade pip build
          python -m pip install pytest pytest-cov hypothesis mypy ruff black
      - name: Run tests and check coverage
        id: test
        run: |
          python -m pytest --cov=odin_ope --cov-report=xml --cov-report=html --cov-fail-under=90
        env:
          PYTHONPATH: src
      - name: Lint
        run: |
          ruff check src/odin_ope
          ruff format --check src/odin_ope
          black --check src/odin_ope
      - name: Type check
        run: |
          mypy --config-file mypy.ini src/odin_ope
      - name: Upload coverage HTML if failed
        if: failure() && steps.test.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov/
      - name: Build
        run: python -m build
      - name: Generate build provenance (SLSA)
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: "dist/*"
      - name: Generate SBOM
        run: |
          python scripts/gen_sbom.py --out sbom.json
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # Expect PYPI_API_TOKEN to be set in repo secrets
          password: ${{ secrets.PYPI_API_TOKEN }}
